# Generated by Django 4.2.3 on 2023-07-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('total_products', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number_of_products', models.PositiveIntegerField()),
                ('payment_options', models.CharField(max_length=32)),
            ],
        ),
    ]
